feat: ✨ add syn-icon-button
synergy-design-system/synergy-design-system pull request #211
Opened 2023-12-05 12:46 UTC by kirchsuSICKAG

# Pull Request

## 📖 Description

This PR adds support for the <syn-icon-button /> component. It includes:

- The vendored component
- Storybook stories
- The generated angular, react and vue wrappers

### 🎫 Issues

Closes #167 

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

## ✅ DoD

- [ ] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [ ] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] I have made sure to follow the projects coding and contribution guides.
- [ ] I have made sure that the bundle size has changed appropriately.
- [ ] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

2023-12-05 12:52 UTC, schilchSICKAG approved these changes

2023-12-05 13:00 UTC, schilchSICKAG submitted a review, later dismissed

2023-12-05 13:05 UTC, schilchSICKAG submitted a review, later dismissed

2023-12-06 05:27 UTC, mariohamann requested changes
Would really favor having the size inheritance as a default, so that per default the size is set via current font size (as it's done with the icons).

1. One principle we follow is "prepare for the unknown". By forcing to the sizes, we violate this principle.
2. We introduced the sizes in design to make the usage more convenient and systemized there. Still in Figma it's super easy to just change the size manually – and this is fine. This change in Figma was not meant to force to these sizes, but to make the usage easier. My understanding of this adoption would be: We offer the sizes, without forcing to them. If this now leads to problems, I would more go the route of removing the size in design and instead point to the spacing scale and show how to resize the element. Maybe that really would make everything easier. @LeaLeRose
3. Or proposed compromise would be: Provide the sizes, make clear on both sides, that's it's resizable to individual needs. And stick to size inheritance per default on dev side. ;)

2023-12-06 07:21 UTC, reichst1SICKAG commented
> Would really favor having the size inheritance as a default, so that per default the size is set via current font size (as it's done with the icons).
> 
>     1. One principle we follow is "prepare for the unknown". By forcing to the sizes, we violate this principle.
> 
>     2. We introduced the sizes in design to make the usage more convenient and systemized there. Still in Figma it's super easy to just change the size manually – and this is fine. This change in Figma was not meant to force to these sizes, but to make the usage easier. My understanding of this adoption would be: We offer the sizes, without forcing to them. If this now leads to problems, I would more go the route of removing the size in design and instead point to the spacing scale and show how to resize the element. Maybe that really would make everything easier. @LeaLeRose
> 
>     3. Or proposed compromise would be: Provide the sizes, make clear on both sides, that's it's resizable to individual needs. And stick to size inheritance per default on dev side. ;)

I assume you only refer to the syn-icon-button (and the syn-icon) with this flexible sizing. 

Nevertheless I would prefer option 3, so that the sizes initially match the other elements and they can be easily inserted with them, but can be adapted "if the icon just doesn't look good". 

Most of the users will just use the provided sizes and be happy if the can sometimes adapt them.

2023-12-06 09:25 UTC, kirchsuSICKAG commented
@mariohamann  @reichst1SICKAG  @LeaLeRose 
But one question will then be open: 
Which padding should the inherited icon-button get? Because every size has it`s own padding:
small -> 12px
medium -> 8px
large -> 16px
inherit -> ??

2023-12-06 09:31 UTC, mariohamann commented
Oh. The icon-buton has several paddings now? That could be a problem. @LeaLeRose Do we need different paddings in design? The shoelace one just has everywhere the same padding:

![Uploading CleanShot 2023-12-06 at 10.31.13@2x.png…]()

2024-01-05 15:17 UTC, mariohamann submitted a review, later dismissed

2024-01-11 11:49 UTC, mariohamann approved these changes

2024-01-11 11:49 UTC, mariohamann commented on packages/components/package.json
>    }
Remember to remove this. :)

2024-01-11 13:52 UTC, merged