chore: 🔧 Upgrade packages to latest
synergy-design-system/synergy-design-system pull request #305
Opened 2024-02-05 13:43 UTC by schilchSICKAG

# Pull Request

## 📖 Description

This PR upgrades (most) packages to their latest stable version. Exceptions are:

- `semantic-release` (does not work with `semantic-release-monorepo@7.x`)
- `semantic-release-monorepo` (Patch does not apply for current 7.0.8 or 8.0.0)
- `change-case` (Multiple backwards-incompatible changes, needs deeper checks)

### 🎫 Issues

- Adresses #258 for the time being (except the packages mentioned above)

## 👩‍💻 Reviewer Notes

- As playwright was also upgraded, make sure to upgrade your local playwright browsers too (`pnpm exec playwright install`)

## 📑 Test Plan

- Check out the branch and issue an `pnpm i -r && pnpm lint && pnpm build`. Everything should work fine
- Start up all the demos and storybook and check if they behave correctly
- Validate there are no differences in wrapper project code when building the wrappers
- Check if storybook still has functioning knobs

## ✅ DoD

- [x] I have tested my changes manually.
- [ ] ~~I have added automatic tests for my changes (unit- and visual regression tests).~~
- [ ] ~~I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).~~
- [x] I have made sure to follow the projects coding and contribution guides.
- [ ] ~~I have made sure that the bundle size has changed appropriately.~~
- [ ] ~~I have validated that there are no accessibility errors.~~
- [ ] ~~I have used design tokens instead of fix css values~~

2024-02-05 16:26 UTC, kirchsuSICKAG requested changes

2024-02-07 08:36 UTC, schilchSICKAG commented on .github/workflows/quality-check.yml
> -      image: mcr.microsoft.com/playwright:v1.39.0-jammy
Yes, I have seen this. This would mean we are not able to upgrade to latest playwright version, but have to use 1.41.2 for the time being

2024-02-07 08:38 UTC, schilchSICKAG commented on packages/components/scripts/jobs/vue/tsc.js
> +  `vue-tsc --project ${baseDir}/tsconfig.json --declaration --outDir "${outDir}"`,
You are right, adjusted this already.

2024-02-07 08:39 UTC, schilchSICKAG commented on packages/_private/vue-demo/package.json
> -    "npm-run-all2": "^6.1.1",
Those are leftovers from the default vite started, I opted to remove them as they are unused on our side.

2024-02-07 08:39 UTC, schilchSICKAG commented on packages/_private/vue-demo/package.json
This stems from the --noEmit error below. Fixed.

2024-02-07 08:41 UTC, schilchSICKAG commented on package.json
> +    "prettier": "^3.2.5"
I opted to remove the trailing `,` as they are invalid JSON anyways, even if tsconfig is not a real JSON file in the first place. The original behavior for prettier was to add them, I think we should just stick to the standards here. What do you think?

2024-02-07 13:26 UTC, kirchsuSICKAG commented on package.json
> +    "prettier": "^3.2.5"
I fully agree with you. Let`s stick to the standards

2024-02-07 13:28 UTC, kirchsuSICKAG approved these changes

2024-02-07 13:30 UTC, kirchsuSICKAG approved these changes

2024-02-07 13:32 UTC, merged