added form tests
synergy-design-system/synergy-design-system pull request #330
Opened 2024-02-19 12:34 UTC by klaarseSICKAG

# Pull Request

## 📖 Description

Playwright tests for form-element demo.
CI integration will follow...

### 🎫 Issues

#260 

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

Check if tests are sufficient.
Tests should be green.

## ✅ DoD

- [ ] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [ ] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] I have made sure to follow the projects coding and contribution guides.
- [ ] I have made sure that the bundle size has changed appropriately.
- [ ] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

2024-02-23 10:36 UTC, schilchSICKAG requested changes

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/package.json
> +    "test": "run-p vanilla_test vue_test react_test ng_test",
If we apply the naming changes, this would be something more like

```suggestion
    "test": "run-p vanilla.run vue.run react.run ng.run",
```

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/package.json
> +  "name": "@synergy-design-system/vanilla-demo",
Copy and paste, should be:

```suggestion
  "name": "@synergy-design-system/e2e-demo-test",
```

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/package.json
> +    "@types/node": "^20.11.16",
Is this a leftover or do we really need this?

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> +
I think I would remove this header completely.

```suggestion
```

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> + * Gauge visual regression test class
I would opt to remove this comment

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> +   * @param _browser - _browser
This parameter is not available or used, should be removed.

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> +   * @param _scriptName - _scriptName
This parameter is not available or used, should be removed.

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> +import locators from './test.selector';
I think the naming here is kind of off. The `test.selector` file includes the selectors. This is also seen in the types of `locator`, which uses a `selector` as its first argument. Suggestion: Rename potentially misleading import declaration `locators` and rename it `selectors`.

```suggestion
import selectors from './test.selector';
```

2024-02-23 10:36 UTC, schilchSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> +  constructor(private page: Page) {
Just curious: Is this done via auto-binding? I do see the references to `this.page` in the code, but it is not set in the constructor or anywhere else.

2024-03-18 14:48 UTC, klaarseSICKAG commented on packages/_private/e2e-demo-test/src/test.page.ts
> + * Gauge visual regression test class
oops

2024-03-22 13:41 UTC, schilchSICKAG approved these changes

2024-03-22 13:45 UTC, merged