feat: ✨ syn-details
synergy-design-system/synergy-design-system pull request #468
Opened 2024-05-06 07:31 UTC by schilchSICKAG

# Pull Request

## 📖 Description

This PR adds the new `<syn-details>` and `<syn-accordion>` components.

### 🎫 Issues

- Closes #462
- Closes #464

## 👩‍💻 Reviewer Notes

Next to the new components, the following adjustments where made that have to be checked:

- A new size-token `syn-spacing-medium-large` was added. It points to a size of `20px` and sits between the `syn-spacing-medium` (`16px`) and `syn-spacing-large` (`24px`) tokens.
- The documentation tokens originally in branch `origin/feat/change-syn-details-docs` where included into this dev-branch.

## 📑 Test Plan

- As usual compare the stories in Storybook
- Have a look at the code of `<syn-accordion>` and make sure everything works and is accessible.

## ✅ DoD

- [x] I have tested my changes manually.
- [x] I have added automatic tests for my changes (unit- and visual regression tests).
- [x] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [x] I have added documentation to the DaVinci migration guide (if need be)
- [x] I have made sure to follow the projects coding and contribution guides.
- [x] I have made sure that the bundle size has changed appropriately.
- [x] I have validated that there are no accessibility errors.
- [x] I have used design tokens instead of fix css values

2024-05-08 12:54 UTC, kirchsuSICKAG requested changes

2024-05-08 13:28 UTC, schilchSICKAG commented on packages/components/src/components/details/details.custom.styles.ts
> +    font-size: var(--syn-font-size-large);
I swear it was different yesterday :). Fixed it

2024-05-08 13:29 UTC, schilchSICKAG commented on packages/components/src/components/details/details.custom.styles.ts
> +    font-size: var(--syn-spacing-x-large);
I swear it was different yesterday :). Fixed it

2024-05-08 13:33 UTC, schilchSICKAG commented on packages/components/src/components/accordion/accordion.component.ts
> +  @property({ attribute: 'close-others', type: Boolean }) closeOthers = false;
Shoelace does not handle this, too. I also thought about if we should implement this. As we do not know what users want to do, I would still go with the current version. I do not want to come into the way of the user if he opens 5 or 10 of the `<syn-details>` elements and through some change in the code they all close automatically ;)

2024-05-08 13:34 UTC, schilchSICKAG commented on packages/components/src/components/accordion/accordion.component.ts
> +      <div part="">
Error during copying, good catch ;)

2024-05-08 13:49 UTC, schilchSICKAG commented on packages/components/src/components/accordion/accordion.test.ts
> +describe('<syn-accordion>', () => {
Done

2024-05-08 13:49 UTC, schilchSICKAG commented on packages/components/src/components/accordion/accordion.component.ts
> + * @slot - The accordion's main content.
Done

2024-05-08 13:49 UTC, schilchSICKAG commented on packages/components/src/components/accordion/accordion.component.ts
> +  /** The size that should be applied to all `<syn-detail>`'s */
Done

2024-05-08 15:10 UTC, kirchsuSICKAG commented on packages/components/src/components/accordion/accordion.component.ts
> +  @property({ attribute: 'close-others', type: Boolean }) closeOthers = false;
Thats fine for me, if we let it as it is  👍

2024-05-13 08:03 UTC, klaarseSICKAG commented
Accordion also done! Nice work!
I am not so sure about the default size though. Medium looks so large. I'd rather go for small as default.

2024-05-13 08:19 UTC, kirchsuSICKAG approved these changes

2024-05-29 04:47 UTC, mariohamann commented on packages/components/src/components/details/details.custom.styles.ts
> +  }
@LeaLeRose I'm not sure if this is good. IMO we should stick to our current convention and make the whole element look disabled, including the border at the bottom.

2024-05-29 04:51 UTC, mariohamann commented
@kirchsuSICKAG What do you think about taking this one over? As you already got some experience with `sharp` and `contained` this could make sense?

2024-06-14 13:42 UTC, klaarseSICKAG commented
please review migration guide: https://gitlab.sick.com/platforms/davinci/synergymigrationguide/-/merge_requests/1

2024-06-20 12:32 UTC, kirchsuSICKAG approved these changes

2024-06-21 08:12 UTC, merged