fix: 🐛 Various issues with syn-prio-nav
synergy-design-system/synergy-design-system pull request #645
Opened 2024-10-02 08:47 UTC by schilchSICKAG

# Pull Request

## 📖 Description

This PR acts as an umbrella for various tickets related to the `<syn-prio-nav>` and `<syn-nav-item>` components.

### 🎫 Issues

Closes #644 
Closes #582
Closes #631
Closes #410
Closes #409
Closes #639

## 👩‍💻 Reviewer Notes

This PR is used to add multiple fixes to our navigation items. It is easier to review those tickets in one scope, so we created an umbrella ticket housing all changes.

## 📑 Test Plan

The following list of steps describes all issues and their related tests:

### Issue #631

Before: https://codepen.io/schilchSICKAG/pen/LYwGraY?editors=1110
After: http://localhost:6006/?path=/docs/components-syn-prio-nav--docs

tl;dr: When using a href attribute, the alignment must now always fit in horizontal mode. The default story of `<syn-prio-nav>` was adjusted to include a `<syn-nav-item>` with a href attribute to check this also in visual integration.

## ✅ DoD

- [ ] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [ ] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] I have added documentation to the DaVinci migration guide (if need be)
- [ ] I have made sure to follow the projects coding and contribution guides.
- [ ] I have made sure that the bundle size has changed appropriately.
- [ ] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

2024-10-10 14:55 UTC, kirchsuSICKAG commented
I just checked it, following issue is also fixed with this PR: #630

2024-10-10 15:02 UTC, kirchsuSICKAG commented
> ### Issue #410
> Open question: I have currently the marker internally in the method:
>
>It would be possible to let users control this behavior if we would use an attribute for this (e.g. something like <syn-prio->nav items-before-menu-visible="2"></syn-prio-nav>. Anyone seeing any value in this?

From my feeling I would say no, I don't really see a value. 
For the moment I would leave it as it is. If someone needs the feature / asks for it, we could add it later.

2024-10-10 15:13 UTC, kirchsuSICKAG commented
> ### Issue #409
>
>Note: We could also have adjusted the code to make sure the handleWidth is only called when the horizontal attribute is set. From a code perspective, this would have various advantages, like calling the listener only when NOT in horizontal mode. If wanted, we could do this easily, too by adding a @watch decorator to the horizontal and pausing / starting the ResizeObserver if it is true. Let´s discuss this. The current solution is working fine either way.

I like this proposal! It makes it clear in the code, that the multiline and the prefix-only styling is only needed, if `horizontal=false`.

2024-10-10 15:14 UTC, kirchsuSICKAG requested changes

2024-10-11 09:58 UTC, schilchSICKAG commented
> > ### Issue #409
> > Note: We could also have adjusted the code to make sure the handleWidth is only called when the horizontal attribute is set. From a code perspective, this would have various advantages, like calling the listener only when NOT in horizontal mode. If wanted, we could do this easily, too by adding a @watch decorator to the horizontal and pausing / starting the ResizeObserver if it is true. Let´s discuss this. The current solution is working fine either way.
> 
> I like this proposal! It makes it clear in the code, that the multiline and the prefix-only styling is only needed, if `horizontal=false`.

Done in the latest version

2024-10-11 10:11 UTC, schilchSICKAG commented
> > ### Issue #409
> > Note: We could also have adjusted the code to make sure the handleWidth is only called when the horizontal attribute is set. From a code perspective, this would have various advantages, like calling the listener only when NOT in horizontal mode. If wanted, we could do this easily, too by adding a @watch decorator to the horizontal and pausing / starting the ResizeObserver if it is true. Let´s discuss this. The current solution is working fine either way.
> 
> I like this proposal! It makes it clear in the code, that the multiline and the prefix-only styling is only needed, if `horizontal=false`.

This is now fixed

2024-10-11 10:11 UTC, schilchSICKAG commented on packages/components/src/components/nav-item/nav-item.styles.ts
> +  :host(:not([horizontal])) .nav-item--has-suffix.nav-item--has-prefix .nav-item__content-container {
Should be resolved with the changes to the underlying resizeObserver

2024-10-11 10:25 UTC, kirchsuSICKAG approved these changes

2024-10-11 10:33 UTC, merged