fix: 🐛 syn-prio-nav takes size of prio menu into account when it's not shown
synergy-design-system/synergy-design-system pull request #665
Opened 2024-11-04 13:26 UTC by schilchSICKAG

# Pull Request

## 📖 Description

This PR adds a fix that makes sure the size of the prio nav menu is not taken into account if it is not visible at all, saving some 50 pixels in the calculation and therefore making it possible to show another item in edge cases.

### 🎫 Issues

Closes #651 

## 👩‍💻 Reviewer Notes

Changes from the [original implementation](https://github.com/synergy-design-system/synergy-design-system/pull/646/commits/7e5f2ff727501f878e362835cf0059750f77b3df) where taken into account, however the fix seems to be relatively easy to do without resorting to reverse list calculations, so I opted to created a smaller version based on the code that we currently have.

## 📑 Test Plan

Play around with storybook, removing the fixed widths from the samples.

## ✅ DoD

- [x] I have tested my changes manually.
- [x] I have added automatic tests for my changes (unit- and visual regression tests).
- [x] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] ~~I have added documentation to the DaVinci migration guide (if need be)~~
- [x] I have made sure to follow the projects coding and contribution guides.
- [ ] ~~I have made sure that the bundle size has changed appropriately.~~
- [x] I have validated that there are no accessibility errors.
- [x] I have used design tokens instead of fix css values

2024-11-05 13:44 UTC, kirchsuSICKAG requested changes

2024-11-05 13:44 UTC, kirchsuSICKAG commented on packages/components/src/components/prio-nav/prio-nav.component.ts
We should not do the check for **>=** on line 166 for the `parseFloat(item.dataset.right!) >= finalWidth)` but just do an **>** so it is `parseFloat(item.dataset.right!) >= finalWidth)`
Otherwise it already shrink for a syn-prio-nav width of 720px although there is 1px spacing left:

![Bildschirmfoto 2024-11-05 um 14 31 25](https://github.com/user-attachments/assets/1ea730e5-6a19-4e3b-8177-b16df3659b9e)

```html
<div style="width:720px; background-color: red;">
  Nav set to 720px, it shrinks the last item even though it actually fits.
</div>
<syn-prio-nav style="width: 720px">
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>1</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>2</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>3</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>4</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>5</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>6</syn-nav-item>
</syn-prio-nav>
<div style="width:721px; background-color: red;">
  Nav set to 721px, all items fit
</div>
<syn-prio-nav style="width: 721px">
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>1</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>2</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>3</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>4</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>5</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>6</syn-nav-item>
</syn-prio-nav>

<style>
  syn-prio-nav {
    background-color: yellow;
  }
  syn-nav-item {
  background: rgba(0,0,200,0.5);
}
</style>
```

2024-11-05 13:44 UTC, kirchsuSICKAG commented on packages/components/src/components/prio-nav/prio-nav.component.ts
It was probably already there before, but I just discovered this weird behavior. It seems there is something wrong, when resizing the prio-nav so the last item should already have enough space to show up, but it doesn't (see gif)

![prio-nav](https://github.com/user-attachments/assets/c6c729e9-1657-4553-adfb-2c91d30a4b05)

```html
<div style="width:calc(600px + calc(var(--syn-spacing-large) * 5)); background-color: red;">
  Nav without any size set, see how all items fit within the 720px width
</div>
 <syn-prio-nav >
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>1</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>2</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>3</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>4</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>5</syn-nav-item>
        <syn-nav-item style="width: 100px; flex-shrink: 0;" horizontal>6</syn-nav-item>
</syn-prio-nav>


<style>
  syn-prio-nav {
    background-color: yellow;
  }
  syn-nav-item {
  background: rgba(0,0,200,0.5);
}
</style>
```

**EDIT**
just found out what the problem is.
we need to adapt line 165-167 to something like this:
```js
 const itemVisibilities = navItems.map((item, index) => {
      const newWidth = index === navItems.length - 1 ? width : finalWidth;
      const isHidden = !!(firstHiddenItemRightPos || parseFloat(item.dataset.right!) > newWidth);
 ```
 
 If it is the last item, we need to take the width of the prio-nav and not the `width minus prioMenuSize` into account

2024-11-08 07:46 UTC, schilchSICKAG commented on packages/components/src/components/prio-nav/prio-nav.component.ts
Fixed in latest version

2024-11-08 07:46 UTC, schilchSICKAG commented on packages/components/src/components/prio-nav/prio-nav.component.ts
That was a good catch! Fixed in latest version

2024-11-08 07:56 UTC, kirchsuSICKAG approved these changes

2024-11-08 08:36 UTC, merged